package com.slai.cmarms.model

import com.slai.cmarms.R

class Caliber(val titleId : Int, val value : String) {

    companion object {

        lateinit var storedList : ArrayList<Caliber>
        
        fun getCalibers() : List<Caliber> {
            if(!::storedList.isInitialized) {
                storedList = ArrayList<Caliber>()
                storedList.add(Caliber(R.string.caliber_10_gauge, "10-gauge"))
                storedList.add(Caliber(R.string.caliber_10_mm, "10-mm"))
                storedList.add(Caliber(R.string.caliber_12, "12-gauge"))
                storedList.add(Caliber(R.string.caliber_16, "16-gauge"))
                storedList.add(Caliber(R.string.caliber_17_two, "17-hm2"))
                storedList.add(Caliber(R.string.caliber_17_r, "17-hmr"))
                storedList.add(Caliber(R.string.caliber_22_hornet, ""))
                storedList.add(Caliber(R.string.caliber_17_remington, ""))
                storedList.add(Caliber(R.string.caliber_17_remington_fireball, ""))
                storedList.add(Caliber(R.string.caliber_17_WSM, ""))

                storedList.add(Caliber(R.string.caliber_20_gauge, ""))
                storedList.add(Caliber(R.string.caliber_204, ""))
                storedList.add(Caliber(R.string.caliber_22_hornet, ""))
                storedList.add(Caliber(R.string.caliber_22_long_rifle, ""))
                storedList.add(Caliber(R.string.caliber_22_magnum, ""))
                storedList.add(Caliber(R.string.caliber_22_short, ""))
                storedList.add(Caliber(R.string.caliber_22_WMR, ""))
                storedList.add(Caliber(R.string.caliber_22_250_remington, ""))
                storedList.add(Caliber(R.string.caliber_220, ""))
                storedList.add(Caliber(R.string.caliber_221, ""))
                storedList.add(Caliber(R.string.caliber_222, ""))
                storedList.add(Caliber(R.string.caliber_223_WSSM, ""))
                storedList.add(Caliber(R.string.caliber_223_wylde, ""))
                storedList.add(Caliber(R.string.caliber_223_556, ""))
                storedList.add(Caliber(R.string.caliber_224, ""))
                storedList.add(Caliber(R.string.caliber_224_weatherby, ""))
                storedList.add(Caliber(R.string.caliber_225, ""))
                storedList.add(Caliber(R.string.caliber_240, ""))
                storedList.add(Caliber(R.string.caliber_243, ""))
                storedList.add(Caliber(R.string.caliber_25_acp, ""))
                storedList.add(Caliber(R.string.caliber_25_wssm, ""))
                storedList.add(Caliber(R.string.caliber_25_06, ""))
                storedList.add(Caliber(R.string.caliber_25_20, ""))
                storedList.add(Caliber(R.string.caliber_257, ""))
                storedList.add(Caliber(R.string.caliber_257_weatherby, ""))
                storedList.add(Caliber(R.string.caliber_260, ""))
                storedList.add(Caliber(R.string.caliber_264, ""))
                storedList.add(Caliber(R.string.caliber_270_weatherby, ""))
                storedList.add(Caliber(R.string.caliber_270, ""))
                storedList.add(Caliber(R.string.caliber_270_wsm, ""))
                storedList.add(Caliber(R.string.caliber_28_gauge, ""))
                storedList.add(Caliber(R.string.caliber_280, ""))
                storedList.add(Caliber(R.string.caliber_280_remington, ""))

                storedList.add(Caliber(R.string.caliber_30_carbine, ""))
                storedList.add(Caliber(R.string.caliber_30_luger, ""))
                storedList.add(Caliber(R.string.caliber_30_thompson, ""))
                storedList.add(Caliber(R.string.caliber_30_06, ""))
                storedList.add(Caliber(R.string.caliber_30_30, ""))
                storedList.add(Caliber(R.string.caliber_30_378, ""))
                storedList.add(Caliber(R.string.caliber_30_40, ""))
                storedList.add(Caliber(R.string.caliber_300_blackout, ""))
                storedList.add(Caliber(R.string.caliber_300_magnum, ""))
                storedList.add(Caliber(R.string.caliber_300_remington_short, ""))
                storedList.add(Caliber(R.string.caliber_300_remington, ""))
                storedList.add(Caliber(R.string.caliber_300_ruger, ""))
                storedList.add(Caliber(R.string.caliber_300_savage, ""))
                storedList.add(Caliber(R.string.caliber_300_weatherby, ""))
                storedList.add(Caliber(R.string.caliber_300_winchester, ""))
                storedList.add(Caliber(R.string.caliber_300_winchester_short, ""))
                storedList.add(Caliber(R.string.caliber_303, ""))
                storedList.add(Caliber(R.string.caliber_307, ""))
                storedList.add(Caliber(R.string.caliber_308, ""))
                storedList.add(Caliber(R.string.caliber_308_winchester, ""))
                storedList.add(Caliber(R.string.caliber_308_762, ""))
                storedList.add(Caliber(R.string.caliber_32_ACP, ""))
                storedList.add(Caliber(R.string.caliber_32_NAA, ""))
                storedList.add(Caliber(R.string.caliber_32_SW, ""))
                storedList.add(Caliber(R.string.caliber_32_SW_long, ""))
                storedList.add(Caliber(R.string.caliber_32_short, ""))
                storedList.add(Caliber(R.string.caliber_32_winchester, ""))
                storedList.add(Caliber(R.string.caliber_32_20, ""))
                storedList.add(Caliber(R.string.caliber_32_40, ""))
                storedList.add(Caliber(R.string.caliber_325, ""))
                storedList.add(Caliber(R.string.caliber_327, ""))
                storedList.add(Caliber(R.string.caliber_338, ""))
                storedList.add(Caliber(R.string.caliber_338_lapue, ""))
                storedList.add(Caliber(R.string.caliber_338_marlin, ""))
                storedList.add(Caliber(R.string.caliber_338_remington, ""))
                storedList.add(Caliber(R.string.caliber_338_ruger, ""))
                storedList.add(Caliber(R.string.caliber_338_winchester, ""))
                storedList.add(Caliber(R.string.caliber_338_378, ""))
                storedList.add(Caliber(R.string.caliber_340, ""))
                storedList.add(Caliber(R.string.caliber_348, ""))
                storedList.add(Caliber(R.string.caliber_35_remington, ""))

                storedList.add(Caliber(R.string.caliber_35_whelen, ""))
                storedList.add(Caliber(R.string.caliber_350, ""))
                storedList.add(Caliber(R.string.caliber_356, ""))
                storedList.add(Caliber(R.string.caliber_357, ""))
                storedList.add(Caliber(R.string.caliber_357_sig, ""))
                storedList.add(Caliber(R.string.caliber_358, ""))
                storedList.add(Caliber(R.string.caliber_36, ""))
                storedList.add(Caliber(R.string.caliber_370, ""))
                storedList.add(Caliber(R.string.caliber_375, ""))
                storedList.add(Caliber(R.string.caliber_375_remington, ""))
                storedList.add(Caliber(R.string.caliber_375_ruger, ""))
                storedList.add(Caliber(R.string.caliber_375_weatherby, ""))
                storedList.add(Caliber(R.string.caliber_375_winchester, ""))
                storedList.add(Caliber(R.string.caliber_376, ""))
                storedList.add(Caliber(R.string.caliber_378, ""))
                storedList.add(Caliber(R.string.caliber_38, ""))
                storedList.add(Caliber(R.string.caliber_38_special, ""))
                storedList.add(Caliber(R.string.caliber_38_short, ""))
                storedList.add(Caliber(R.string.caliber_38_super, ""))
                storedList.add(Caliber(R.string.caliber_38_40, ""))
                storedList.add(Caliber(R.string.caliber_38_55, ""))
                storedList.add(Caliber(R.string.caliber_380, ""))

                storedList.add(Caliber(R.string.caliber_46_30, ""))
                storedList.add(Caliber(R.string.caliber_40, ""))
                storedList.add(Caliber(R.string.caliber_40_sw, ""))
                storedList.add(Caliber(R.string.caliber_400, ""))
                storedList.add(Caliber(R.string.caliber_404, ""))
                storedList.add(Caliber(R.string.caliber_405, ""))
                storedList.add(Caliber(R.string.caliber_41, ""))
                storedList.add(Caliber(R.string.caliber_41_remington, ""))
                storedList.add(Caliber(R.string.caliber_410, ""))
                storedList.add(Caliber(R.string.caliber_416, ""))
                storedList.add(Caliber(R.string.caliber_416_rigby, ""))
                storedList.add(Caliber(R.string.caliber_416_ruger, ""))
                storedList.add(Caliber(R.string.caliber_416_weatherby, ""))
                storedList.add(Caliber(R.string.caliber_44_black, ""))
                storedList.add(Caliber(R.string.caliber_44_magnum, ""))
                storedList.add(Caliber(R.string.caliber_44_rimfire, ""))
                storedList.add(Caliber(R.string.caliber_44_special, ""))
                storedList.add(Caliber(R.string.caliber_44_70, ""))
                storedList.add(Caliber(R.string.caliber_444, ""))
                storedList.add(Caliber(R.string.caliber_45_acp, ""))
                storedList.add(Caliber(R.string.caliber_45_acp, ""))
                storedList.add(Caliber(R.string.caliber_45_auto, ""))
                storedList.add(Caliber(R.string.caliber_45_black, ""))
                storedList.add(Caliber(R.string.caliber_45_colt, ""))
                storedList.add(Caliber(R.string.caliber_45_gap, ""))
                storedList.add(Caliber(R.string.caliber_45_long, ""))
                storedList.add(Caliber(R.string.caliber_45_100, ""))
                storedList.add(Caliber(R.string.caliber_45_70, ""))
                storedList.add(Caliber(R.string.caliber_45_90, ""))
                storedList.add(Caliber(R.string.caliber_450, ""))
                storedList.add(Caliber(R.string.caliber_450_marlin, ""))
                storedList.add(Caliber(R.string.caliber_450_nitro, ""))
                storedList.add(Caliber(R.string.caliber_450_rigby, ""))
                storedList.add(Caliber(R.string.caliber_450_400, ""))
                storedList.add(Caliber(R.string.caliber_454, ""))
                storedList.add(Caliber(R.string.caliber_458, ""))
                storedList.add(Caliber(R.string.caliber_458_socom, ""))
                storedList.add(Caliber(R.string.caliber_458_winchester, ""))
                storedList.add(Caliber(R.string.caliber_460, ""))
                storedList.add(Caliber(R.string.caliber_460_weatherby, ""))
                storedList.add(Caliber(R.string.caliber_470, ""))
                storedList.add(Caliber(R.string.caliber_475, ""))
                storedList.add(Caliber(R.string.caliber_480, ""))

                storedList.add(Caliber(R.string.caliber_545, ""))
                storedList.add(Caliber(R.string.caliber_556, ""))
                storedList.add(Caliber(R.string.caliber_56, ""))
                storedList.add(Caliber(R.string.caliber_57, ""))
                storedList.add(Caliber(R.string.caliber_50, ""))
                storedList.add(Caliber(R.string.caliber_50_beowulf, ""))
                storedList.add(Caliber(R.string.caliber_50_black, ""))
                storedList.add(Caliber(R.string.caliber_50_BMG, ""))
                storedList.add(Caliber(R.string.caliber_500_nitro, ""))
                storedList.add(Caliber(R.string.caliber_500_sw, ""))
                storedList.add(Caliber(R.string.caliber_505, ""))
                storedList.add(Caliber(R.string.caliber_52, ""))
                storedList.add(Caliber(R.string.caliber_54, ""))
                storedList.add(Caliber(R.string.caliber_58, ""))

                storedList.add(Caliber(R.string.caliber_6_5, ""))
                storedList.add(Caliber(R.string.caliber_6_5_grendal, ""))
                storedList.add(Caliber(R.string.caliber_6_5_284, ""))
                storedList.add(Caliber(R.string.caliber_6_5_jp, ""))
                storedList.add(Caliber(R.string.caliber_6_5_carcano, ""))
                storedList.add(Caliber(R.string.caliber_6_5_swedish, ""))
                storedList.add(Caliber(R.string.caliber_6_8_spcii, ""))
                storedList.add(Caliber(R.string.caliber_6mm, ""))
                storedList.add(Caliber(R.string.caliber_6mm_remington, ""))

                storedList.add(Caliber(R.string.caliber_75_swiss, ""))
                storedList.add(Caliber(R.string.caliber_76, ""))
                storedList.add(Caliber(R.string.caliber_762, ""))
                storedList.add(Caliber(R.string.caliber_762_nato, ""))
                storedList.add(Caliber(R.string.caliber_762r, ""))
                storedList.add(Caliber(R.string.caliber_765, ""))
                storedList.add(Caliber(R.string.caliber_77, ""))
                storedList.add(Caliber(R.string.caliber_7mm, ""))
                storedList.add(Caliber(R.string.caliber_7mm_remington, ""))
                storedList.add(Caliber(R.string.caliber_7mm_remington_sa, ""))
                storedList.add(Caliber(R.string.caliber_7mm_remington_ultra, ""))
                storedList.add(Caliber(R.string.caliber_7mm_westerner, ""))
                storedList.add(Caliber(R.string.caliber_7mm_weatherby, ""))
                storedList.add(Caliber(R.string.caliber_7mm_winchester, ""))
                storedList.add(Caliber(R.string.caliber_7mm_08, ""))
                storedList.add(Caliber(R.string.caliber_757, ""))
                storedList.add(Caliber(R.string.caliber_764, ""))
                storedList.add(Caliber(R.string.caliber_765r, ""))

                storedList.add(Caliber(R.string.caliber_8mm, ""))
                storedList.add(Caliber(R.string.caliber_8mm_remington, ""))
                storedList.add(Caliber(R.string.caliber_856, ""))
                storedList.add(Caliber(R.string.caliber_857, ""))
                storedList.add(Caliber(R.string.caliber_857_mauser, ""))

                storedList.add(Caliber(R.string.caliber_93_62, ""))
                storedList.add(Caliber(R.string.caliber_93_72, ""))
                storedList.add(Caliber(R.string.caliber_93_74, ""))
                storedList.add(Caliber(R.string.caliber_9mm, ""))
                storedList.add(Caliber(R.string.caliber_9mm_makarov, ""))
                storedList.add(Caliber(R.string.caliber_9_21, ""))
                storedList.add(Caliber(R.string.caliber_9_23_winchester, ""))
                storedList.add(Caliber(R.string.caliber_9_23, ""))
            }
            return storedList
        }
    }
}